# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' First example
#' @param args string vector
#' @export
pontential_in_complete_graph_case <- function(origin, dest, trips, unique_geozomes) {
    .Call(`_HodgePotentialHumanFlow_pontential_in_complete_graph_case`, origin, dest, trips, unique_geozomes)
}

